export const EMBEDDING_DIM = 1024;
export const EMBEDDINGS_URL = "/embeddings.bin";

export interface Influencer {
  id: string;
  name: string;
  followers: string;
  productCount: number;
  bio?: string;
  imageUrl: string;
}

export const categoryNames = {
  tech: "TECH",
  fitness: "FITNESS",
  beauty: "BEAUTY",
  home: "HOME",
  fashion: "FASHION",
} as const;

// Mock data for influencers by category
export const influencersByCategory: Record<string, Influencer[]> = {
  tech: [
    {
      id: "linustechtips",
      name: "Linus Tech Tips",
      followers: "13.8M",
      productCount: 42,
      imageUrl: "/influencers/linustechtips/profile.jpg",
      bio: "Tech reviews, guides, and unboxings from the LTT team",
    },
    {
      id: "ijustine",
      name: "iJustine",
      followers: "7.2M",
      productCount: 36,
      imageUrl: "/influencers/ijustine/profile.jpg",
      bio: "Tech enthusiast covering Apple products, gadgets, and gaming",
    },
    {
      id: "mkbhd",
      name: "MKBHD",
      followers: "16.5M",
      productCount: 28,
      imageUrl: "/influencers/mkbhd/profile.jpg",
      bio: "Quality tech videos and in-depth product reviews",
    },
    {
      id: "unboxtherapy",
      name: "Unbox Therapy",
      followers: "18.2M",
      productCount: 45,
      imageUrl: "/influencers/unboxtherapy/profile.jpg",
      bio: "Unboxing and reviewing the latest tech gadgets",
    },
  ],
  fitness: [
    {
      id: "garagegymreviews",
      name: "Garage Gym Reviews",
      followers: "600K",
      productCount: 20,
      imageUrl: "/influencers/garagegymreviews/profile.jpg",
      bio: "Home workouts, fitness tips, and healthy lifestyle recommendations",
    },
    {
      id: "andreajeanco",
      name: "Andrea Jean Co",
      followers: "800K",
      productCount: 15,
      imageUrl: "/influencers/andreajeanco/profile.jpg",
      bio: "Amazon fashion & home finds, fitness tips, and lifestyle content",
    },
  ],
  beauty: [],
  home: [],
  fashion: [],
};

export const TAGS = [
  "lotion",
  "box",
  "holiday",
  "tension",
  "joke",
  "laptops",
  "prank",
  "foam",
  "stimulator",
  "cream",
  "chocolate",
  "candy",
  "spa",
  "confetti",
  "trendy",
  "collectibles",
  "personal care",
  "novelty",
  "gift",
  "emoji",
  "treats",
  "kitchen",
  "vintage decor",
  "celebration",
  "wearable",
  "movies",
  "bottle",
  "lighting",
  "automotive",
  "music",
  "sports",
  "band",
  "home decor",
  "funny",
  "resistance",
  "travel",
  "elasticity",
  "outdoors",
  "phones",
  "desk toys",
  "seasonal",
  "retro items",
  "massage",
  "workout",
  "sleeve",
  "stationery",
  "graphic",
  "novelty items",
  "ornament",
  "tightening",
  "miniature",
  "brunch",
  "bedding",
  "international",
  "bags",
  "fitness",
  "sci fi merch",
  "crafts",
  "games",
  "fantasy decor",
  "health",
  "glass",
  "mens clothing",
  "electronics",
  "cannon",
  "appliances",
  "vintage",
  "cleaning",
  "detox",
  "muscle",
  "weird",
  "toys",
  "colorful",
  "smart home",
  "recovery",
  "relief",
  "fashion",
  "gag",
  "floral",
  "grocery",
  "swirl",
  "witchy decor",
  "exercise",
  "garden",
  "vases",
  "circulation",
  "school supplies",
  "party",
  "oddities",
  "sweet",
  "fandom collectibles",
  "poop",
  "books",
  "gourmet",
  "decoration",
  "tshirt",
  "pets",
  "casual",
  "device",
  "gaming consoles",
  "beauty",
  "home",
  "miniatures",
  "kawaii",
  "quirky lamps",
  "ems",
  "spicy",
  "watches",
  "anime merch",
  "natural",
  "kids clothing",
  "roller",
  "incense holders",
  "party supplies",
  "pilates",
  "mystical items",
  "womens clothing",
  "gag gifts",
  "audio equipment",
  "shoes",
  "cameras",
  "tens",
  "wall art",
  "soothing",
  "training",
  "snacks",
  "tools",
  "smart",
  "birthday",
  "therapy",
  "statues",
  "organic",
  "summer",
  "figurines",
  "art sculptures",
  "baby",
  "funny signs",
  "cute",
  "crystals",
  "pop culture",
  "jewelry",
  "office",
  "skincare",
  "centerpiece",
  "rustic",
  "exotic",
  "silly",
  "surprise",
  "furniture",
  "snack",
];

export const QWEN_EMBEDDING_SIZE_1B = 1024;
